// <auto-generated />
namespace BE_SpexPAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Renames1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renames1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505191120148_Renames1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
